### ISSUE TITLE
技術選定

### ISSUE THREAD

**Issue by kam6ri** [skinfit/skinfit#10]
MVPを実装するために必要な技術を選定します

**Comment by kam6ri** [comment]
## Frontend
- React + TypeScript
- Tailwind CSS

## Backend
- Python
- OpenAI API

## Database
- supabase
- PostgreSQL

## Hosting
- Vercel or Netlify

**Comment by kam6ri** [comment]
初心者なもので、適当に並べてみました。
ご意見いただけますと幸いです。

**Comment by nagauta** [comment]
@kam6ri 
僕も基本的にご提案のスタックでいい感じだと思っています！！
最初は、BackendもNext.jsだけでいいかもです。
Open APIは[LangChain](https://github.com/hwchase17/langchain)使えばJS系でもいけるので、API 使うだけならJSだけでいいかなと！
supabaseは知らなかったです！無料枠あるようなので使ってみたいです！

**Comment by kam6ri** [comment]
@nagauta 
ありがとうございます。
Next.js初心者なので勉強しながらやっていきます。
最初は最低限の構成で作りたいので、Next.js + LangChain + supabaseでいきましょうか。
